apiVersion: v1
kind: ServiceAccount
metadata:
  name: currency
---
apiVersion: v1
kind: Service
metadata:
  name: currency
spec:
  selector:
    app: currency
  ports:
    - port: 9093
      targetPort: 9093
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: currency
  labels:
    app: currency
    service: fake-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: currency
  template:
    metadata:
      labels:
        app: currency
      annotations:
        consul.hashicorp.com/connect-inject: 'true'
        consul.hashicorp.com/transparent-proxy: 'false'
    spec:
      serviceAccountName: currency
      containers:
        - name: currency
          image: nicholasjackson/fake-service:v0.23.0
          ports:
            - containerPort: 9093
          env:
            - name: 'LISTEN_ADDR'
              value: '127.0.0.1:9093'
            - name: 'NAME'
              value: 'currency'
            - name: 'MESSAGE'
              value: 'currency response'
            - name: 'SERVER_TYPE'
              value: 'grpc'
            - name: 'ERROR_TYPE'
              value: 'http_error'
            - name: 'ERROR_RATE'
              value: '0.2'
            - name: 'ERROR_CODE'
              value: '14'
            - name: 'TRACING_ZIPKIN'
              value: 'http://simplest-collector:9411'