apiVersion: v1
kind: ServiceAccount
metadata:
  name: payments
---
apiVersion: v1
kind: Service
metadata:
  name: payments
spec:
  selector:
    app: payments
  ports:
    - port: 9094
      targetPort: 9094
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments
  labels:
    app: payments
    service: fake-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments
  template:
    metadata:
      labels:
        app: payments
      annotations:
        consul.hashicorp.com/connect-inject: 'true'
        consul.hashicorp.com/transparent-proxy: 'false'
        consul.hashicorp.com/connect-service-upstreams: 'currency:9093'
    spec:
      serviceAccountName: payments
      containers:
        - name: payments
          image: nicholasjackson/fake-service:v0.23.0
          ports:
            - containerPort: 9094
          env:
            - name: 'LISTEN_ADDR'
              value: '127.0.0.1:9094'
            - name: 'UPSTREAM_URIS'
              value: 'grpc://currency:9093'
            - name: 'NAME'
              value: 'payments'
            - name: 'MESSAGE'
              value: 'payments response'
            - name: 'SERVER_TYPE'
              value: 'http'
            - name: 'TRACING_ZIPKIN'
              value: 'http://simplest-collector:9411'