---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: payments
spec:
  destination:
    name: payments
    namespace: payments-ns
  sources:
  - name: api
    namespace: default
    partition: default
    action: allow