# https://github.com/hashicorp/consul-k8s/blob/main/charts/consul/values.yaml
global:
  name: team2
  enabled: false
  enableConsulNamespaces: true
  datacenter: usw2
  adminPartitions:
    enabled: true
    name: "pci"
    #service:
    #  type: LoadBalancer
    # service:
    #   type: NodePort
    #   nodePort:
    #     https: 30001
    #     rpc: 31002
    #     serf: 31003
  acls:
    manageSystemACLs: true
    bootstrapToken:
      secretName: consul-bootstrap-token
      secretKey: token
  gossipEncryption:
    secretName: consul-gossip-key
    secretKey: key
  tls:
    enabled: true
    enableAutoEncrypt: true
    caCert:
      secretName: consul-ca-cert
      secretKey: tls.crt
externalServers:
  enabled: true
  hosts: ["usw2.private.consul.328306de-41b8-43a7-9c38-ca8d89d06b07.aws.hashicorp.cloud"]
  httpsPort: 443
  useSystemRoots: true
  k8sAuthMethodHost: https://5E9E751D9E1BE01516BFAACADB3C0995.sk1.us-west-2.eks.amazonaws.com
client:
  enabled: true
  join: ["usw2.private.consul.328306de-41b8-43a7-9c38-ca8d89d06b07.aws.hashicorp.cloud"]
dns:
  enabled: true
  enableRedirection: true
  clusterIP: 172.21.128.87 # Needed to configure kube-dns forwarding
connectInject:
  enabled: true
  transparentProxy:
    defaultEnabled: true
  metrics:
    defaultEnabled: true # by default, this inherits from the value global.metrics.enabled
    defaultEnableMerging: true
  consulNamespaces:
    mirroringK8S: true
syncCatalog:
  enabled: true
  toConsul: false
  toK8S: true
controller:
  enabled: true
meshGateway:
  enabled: true
  replicas: 1
