apiVersion: v1
kind: ServiceAccount
metadata:
  name: web
  namespace: web
---
apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: web
spec:
  selector:
    app: web
  ports:
    - port: 9090
      targetPort: 9090
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: web
  labels:
    app: web
    service: fake-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      namespace: web
      labels:
        app: web
        service: fake-service
      annotations:
        consul.hashicorp.com/connect-inject: 'true'
        consul.hashicorp.com/transparent-proxy: 'true'
        #consul.hashicorp.com/connect-service-upstreams: 'api.default:9091'
    spec:
      serviceAccountName: web
      containers:
        - name: web
          image: nicholasjackson/fake-service:v0.21.0
          ports:
            - containerPort: 9090
          env:
            - name: 'LISTEN_ADDR'
              value: '0.0.0.0:9090'
            - name: 'UPSTREAM_URIS'
              value: 'http://api.virtual.api.ns.default.ap.usw2.dc.consul/api'
            - name: 'NAME'
              value: 'web'
            - name: 'MESSAGE'
              value: 'Hello World'
            - name: 'SERVER_TYPE'
              value: 'http'
            - name: 'TIMING_50_PERCENTILE'
              value: '30ms'
            - name: 'TIMING_90_PERCENTILE'
              value: '60ms'
            - name: 'TIMING_99_PERCENTILE'
              value: '90ms'
            - name: 'TIMING_VARIANCE'
              value: '10'
            - name: 'HTTP_CLIENT_APPEND_REQUEST'
              value: 'true'
            - name: 'TRACING_ZIPKIN'
              value: 'http://simplest-collector:9411'
