apiVersion: v1
kind: ConfigMap
data:
  Corefile: |
    .:53 {
        errors
        health
        kubernetes cluster.local in-addr.arpa ip6.arpa {
          pods insecure
          fallthrough in-addr.arpa ip6.arpa
        }
        prometheus :9153
        forward . /etc/resolv.conf
        cache 30
        loop
        reload
        loadbalance
    }
    consul:53 {
        errors
        cache 30
        forward . ${CONSUL_DNS_CLUSTER_IP}
    }
metadata:
    name: coredns
    namespace: kube-system
    labels:
        eks.amazonaws.com/component: coredns
        k8s-app: kube-dns