apiVersion: v1
kind: ServiceAccount
metadata:
  name: payments
  namespace: payments
---
apiVersion: v1
kind: Service
metadata:
  name: payments
  namespace: payments
spec:
  selector:
    app: payments
  ports:
    - port: 9090
      targetPort: 9090
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments
  namespace: payments
  labels:
    app: payments
    service: fake-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments
  template:
    metadata:
      namespace: payments
      labels:
        app: payments
        service: fake-service
      annotations:
        consul.hashicorp.com/connect-inject: 'true'
        consul.hashicorp.com/transparent-proxy: 'true'
    spec:
      serviceAccountName: payments
      containers:
        - name: payments
          image: nicholasjackson/fake-service:v0.21.0
          ports:
            - containerPort: 9090
          env:
            - name: 'LISTEN_ADDR'
              value: '127.0.0.1:9090'
            #- name: 'UPSTREAM_URIS'
            #  value: 'grpc://currency.currency-ns:9090'
            - name: 'NAME'
              value: 'payments'
            - name: 'MESSAGE'
              value: 'payments response'
            - name: 'SERVER_TYPE'
              value: 'http'
            - name: 'HTTP_CLIENT_APPEND_REQUEST'
              value: 'true'
            - name: 'TRACING_ZIPKIN'
              value: 'http://simplest-collector.default:9411'